### ISSUE TITLE
Date issue in generated api

### ISSUE THREAD

**Issue by ctatineni** [Netflix/hollow#13]
added java.util.Date to Movie object, and started producer, i am getting the below error.

java.lang.IllegalArgumentException: Attempting to write unexpected class!  Expected class sun.util.calendar.BaseCalendar$Date but object was class java.util.Date
	at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper.write(HollowObjectTypeMapper.java:117)
	at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper$MappedField.copy(HollowObjectTypeMapper.java:275)

**Comment by dkoszewnik** [comment]
Thanks very much for the report!  I verified the issue and released a fix in __v2.1.1__.

Thanks again,
Drew.
