### ISSUE TITLE
It's not possible to start a consumer application when blob store directory is empty

### ISSUE THREAD

**Issue by tdudzik** [Netflix/hollow#140]
When you are trying to start an application and create indexes and your blob store dir is empty the following exceptions are thrown:

- for primary key index:
```
java.lang.NullPointerException
	at com.netflix.hollow.api.client.HollowClientUpdater.getStateEngine(HollowClientUpdater.java:166)
	at com.netflix.hollow.api.consumer.HollowConsumer.getStateEngine(HollowConsumer.java:246)
	at [your-api-package].[IndexName]PrimaryKeyIndex.<init>([IndexName]PrimaryKeyIndex.java:15)
```

- for hash index:
```
java.lang.NullPointerException
	at com.netflix.hollow.api.client.HollowClientUpdater.getAPI(HollowClientUpdater.java:170)
	at com.netflix.hollow.api.consumer.HollowConsumer.getAPI(HollowConsumer.java:260)
	at [your-api-package].[ApiName]APIHashIndex.<init>([ApiName]APIHashIndex.java:25)
```

Both exceptions are related to `HollowClientUpdater#hollowDataHolder` field which is `null` in that case.

**Comment by johnrengelman** [comment]
Been hitting this one pretty regularly and can't seem to find a way to detect it other than wrapping this in `try/catch` for NPEs.

**Comment by brettwooldridge** [comment]
We always just call mkDirs() on the store directory before starting the client.

**Comment by johnrengelman** [comment]
Well, we are writing our own backing (using redis) and get the same problem. I guess I could look to see if it’s something in there. But it seems like the hollow state just doesn’t fully initialize unless there is data.

**Comment by rpalcolea** [comment]
@brettwooldridge @johnrengelman,

I think this is a expected behavior, there was some conversation around this in the Gitter room. I guess the work on this would be a meaningful exception.  

In our case, we initialize the indexes once we triggered a refresh on the consumer and the `StateEngine` is ready. Our implementation pulls the blobs from Google Cloud Storage and keeps a local copy with `LocalBlobStore`. At the end we do the `mkdirs()` and wrap the index creation in a try/catch, something like:

```groovy
ProductPrimaryKeyIndex idx
        consumer = HollowConsumer.withBlobRetriever(gcsBlobRetriever)
                .withLocalBlobStore(new File("//blob-test").mkdirs())
                .withAnnouncementWatcher(announcementWatcher)
                .withGeneratedAPIClass(ProductAPI)
                .withMetricsCollector(productHollowMetricsCollector)
                .build()

        consumer.triggerRefresh()

 boolean indexReady = false
        while (!indexReady) {
            try {
                idx = new ProductPrimaryKeyIndex(consumer, “field")
                indexReady = true
            } catch (Exception e) {
                sleep(1000)
            }
        }
```

Still, @toolbear suggestion is cleaner to guarantee the refresh.

```java
firstRefresh = new CompletableFuture<>();

refreshListener = new RefreshListener() {
    public refreshSuccessful(long beforeVersion, long afterVersion, long requestedVersion) {
        if(beforeVersion == Long.MIN_VALUE)
            firstRefresh.complete(afterVersion);
    }
};

consumer = HollowConsumer.withBlobRetriever(...)
                .withRefreshListener(refreshListener)
                ...
                .build()

 // gate remainder of initialization on future completion
firstRefresh.get();
// build indexes, etc.
```

And yes, the `StateEngine` will be null if there is no data, having data is needed to create indexes. (AFAIK)

Ideally, when your local state dir is empty and you trigger a refresh, it should pull the latest version (either the one announced or one specified by you), download the delta chain (snapshots/deltas) and store them in your local state dir, apply them to the consumer and initialize the state engine (don't know if that's the proper order, but that's the expected result). Once this is ready, you should be able to create indexes

**Comment by tdudzik** [comment]
@rpalcolea these solutions don't solve the problem. The application won't crash but it also won't start. I think the application should start and just don't have any data.

**Comment by rpalcolea** [comment]
oh I get it, but then... why would you like to "create an index" if you don't have data? shouldn't be better to refresh the consumer and create the index once you know there's data available?

**Comment by johnrengelman** [comment]
It’s not just related to index creation. If you generate a hollow api and then start a consumer with that api and call “consumer.getAPI()”, it’ll throw a NPE

**Comment by akhaku** [comment]
Opened up #197 as a proposal to fix this. That PR contains a bit of a cleanup, but the meat of it is in `HollowClientUpdater` - initializing the data state to an empty `HollowReadStateEngine` if there are no published versions. If you `triggerRefresh` after something is published (or wait for `triggerRefreshAsync` to kick in on its own) you will be updated to the latest version via a snapshot update.
An important side-effect of the empty state is that there are _no_ types available in your consumer, so even initializing a `PrimaryKey` will fail. You can check if you have been initialized yet by calling `HollowConsumer#getCurrentVersionId` and comparing it to `HollowConstants#VERSION_NONE`.

**Comment by tdudzik** [comment]
@akhaku so as I understand, after these changes an application won't crash but creating `PrimaryKey` is not possible. So it's needed to implement kind of lazily initialized indexes (currently our indexes are initialized during an application startup) that initializes only when the state is not empty. Am I right?

**Comment by akhaku** [comment]
Yes, you'll want to wait until after a `triggerRefresh` (assuming you have already published data). `triggerRefresh` is a blocking call that will fetch the latest state from your announcement watcher.

If you don't already have published data, you will have to wait until you have data. One way to do that would be to attach a [RefreshListener](https://github.com/Netflix/hollow/blob/master/hollow/src/main/java/com/netflix/hollow/api/consumer/HollowConsumer.java#L581)

**Comment by Mykyta** [comment]
I'm facing with the issue while init HollowConsumer if Hollow's data don't exist.  I can't figure out how exactly RefreshListener will help me to init PrimaryKeyIndex's. Maybe I've missed something and have another good approach to lazy init HollowConsumer without Hollow's data and waiting until HollowProducer publish them.

**Comment by Mykyta** [comment]
I've found only this solution:
Init `HollowConsumer` in the constructor
```
public MyHollowConsumer(BlobRetriever blobRetriever, AnnouncementWatcher announcementWatcher)
    {
        this.blobRetriever = blobRetriever;
        this.announcementWatcher = announcementWatcher;
        HollowConsumer consumer = withBlobRetriever(blobRetriever)
                .withAnnouncementWatcher(announcementWatcher)
                .withRefreshListener(new CustomRefreshListener())
                .build();
       // we can't init Hollow index here, since hollow data could not be exist. 
        consumer.triggerRefresh();
```

And implement `RefreshListener ` to reInit `HollowConsumer `
```
private class CustomRefreshListener extends HollowConsumer.AbstractRefreshListener
    {
        @Override
        public void refreshStarted(long currentVersion, long requestedVersion)
        {
            if (currentVersion == HollowConstants.VERSION_NONE)
            {
                HollowConsumer consumer = withBlobRetriever(blobRetriever)
                        .withAnnouncementWatcher(announcementWatcher)
                        .withGeneratedAPIClass(how.hollow.ti.TiAPI.class)
                        .build();
                consumer.triggerRefresh();
               // we can init Hollow Inex now
                index= new MyPrimaryKeyIndex(consumer);
                hashIdx = new MyAPIHashIndex(consumer);
            }
        }
```
But it looks awful. Maybe someone can suggest another good approach?

**Comment by rpalcolea** [comment]
Hi @Mykyta , I think you want to do the following:

```java
void initialize(HollowConsumer.BlobRetriever blobRetriever, HollowConsumer.AnnouncementWatcher announcementWatcher) throws ExecutionException, InterruptedException {

        CompletableFuture firstRefresh = new CompletableFuture<>();
        HollowConsumer.RefreshListener refreshListener = new HollowConsumer.RefreshListener() {
            public void refreshSuccessful(long beforeVersion, long afterVersion, long requestedVersion) {
                if(beforeVersion == Long.MIN_VALUE)
                    firstRefresh.complete(afterVersion);
            }

            @Override  public void refreshStarted(long currentVersion, long requestedVersion) { }
            @Override public void snapshotUpdateOccurred(HollowAPI api, HollowReadStateEngine stateEngine, long version) throws Exception { }
            @Override public void deltaUpdateOccurred(HollowAPI api, HollowReadStateEngine stateEngine, long version) throws Exception { }
            @Override public void blobLoaded(HollowConsumer.Blob transition) { }
            @Override public void refreshFailed(long beforeVersion, long afterVersion, long requestedVersion, Throwable failureCause) { }
        };

        HollowConsumer consumer = HollowConsumer.withBlobRetriever(blobRetriever)
                .withAnnouncementWatcher(announcementWatcher)
                .withRefreshListener(refreshListener)
                .build();

        consumer.triggerAsyncRefresh();

        firstRefresh.get();

        MyPrimaryKeyIndex index = new MyPrimaryKeyIndex(consumer);
    }
```
where you create a refresh listener that basically completes the `firstRefresh` future…
you create your consumer with this listener and trigger a refresh… then you basically wait for the future to complete by doing `firstRefresh.get()`. 

At that point, if completed, you will have the dataset ready and you should be able to create your index.

Looking at your example in https://github.com/Netflix/hollow/issues/140#issuecomment-398382930, I don’t think you want to create index in refreshStarted.

**Comment by Mykyta** [comment]
Thanks @rpalcolea for this solution. It works for me. I hope in nearest releases will become more graceful solution to solve that issue.

**Comment by ghost** [comment]
We're nearer to a graceful solution in Hollow.

`HollowConsumer` now has `getInitialLoad()` which returns a `CompletableFuture` that completes asynchronously when the first load of data has completed. Example usage:

```java
HollowConsumer consumer = HollowConsumer.withBlobRetriever(blobRetriever)
    .withAnnouncementWatcher(announcementWatcher)
    .build();
consumer.getInitialLoad().join();

MyPrimaryKeyIndex index = new MyPrimaryKeyIndex(consumer);
index.listenToDataRefresh();
```

I've considered having `AbstractHollowUniqueKeyIndex` constructor automatically call, `getInitialLoad().join()` on the provided consumer. We might still do this, but the concern is that the constructor is now blocking and this could lead to deadlock in prior written code that didn't expect this behavior.

We're also looking at some convenience methods on `HollowConsumer` that will lazily cache unique key indices and do all the right things (wait on the consumer, subscribe to updates so that the index stays up-to-date automatically). Something like:

```java
consumer = ….build();

MyPrimaryKeyIndex index = consumer.uniqueKeyIndex(MyPrimaryKeyIndex.class);
```
