### ISSUE TITLE
HollowObjectMapper fails with unhelpful NPE if writing a Map with a null value

### ISSUE THREAD

**Issue by akhaku** [Netflix/hollow#253]
```
Caused by: java.lang.NullPointerException
    at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper.write(HollowObjectTypeMapper.java:170) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowMapTypeMapper.write(HollowMapTypeMapper.java:76) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper$MappedField.copy(HollowObjectTypeMapper.java:470) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper.write(HollowObjectTypeMapper.java:176) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowListTypeMapper.write(HollowListTypeMapper.java:79) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper$MappedField.copy(HollowObjectTypeMapper.java:470) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowObjectTypeMapper.write(HollowObjectTypeMapper.java:176) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.core.write.objectmapper.HollowObjectMapper.add(HollowObjectMapper.java:70) ~[hollow-3.1.0.jar:3.1.0]
    at com.netflix.hollow.api.producer.WriteStateImpl.add(WriteStateImpl.java:41) ~[hollow-3.1.0.jar:3.1.0]
```

We should add a test to reproduce this, and either:
- fail with a more useful error message, or
- make it work

**Comment by PaulSandoz** [comment]
Hollow does not support `null` in collections (see Hollow [documentation](https://hollow.how/advanced-topics/#in-memory-data-layout))). Exceptions should be produced closer to the source elements and with better messages.
