### ISSUE TITLE
Automatic directory creation when generating the API

### ISSUE THREAD

**Issue by fortyrunner** [Netflix/hollow#35]
If I call the API generator for a sub package - the directory isn't generated.

E.g.

```
 String directory = "src/main/java/fortyrunner/generated";

  HollowAPIGenerator generator =
    new HollowAPIGenerator(
        "PrimaryTypes",                    /// A name for the API
        "fortyrunner.generated",  /// A package where the API will live
        writeEngine                    /// our state engine
      );
   generator.generateFiles(directory);

```
What's more, the generateFiles method throws an exception.

```
Exception in thread "main" java.io.FileNotFoundException: src/main/java/fortyrunner/generated/PrimaryTypes.java (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.FileWriter.<init>(FileWriter.java:90)
	at com.netflix.hollow.api.codegen.HollowAPIGenerator.generateFile(HollowAPIGenerator.java:130)

```
I can easily fix this by saying:

```
    String directory = "src/main/java/fortyrunner/generated";

    HollowAPIGenerator generator =
      new HollowAPIGenerator(
        "PrimaryTypes",                    /// A name for the API
        "fortyrunner.generated",  /// A package where the API will live
        writeEngine                    /// our state engine
      );

    Files.createDirectories(Paths.get(directory));

    generator.generateFiles(directory);
```

It's just a bit irritating if I want to write into a sub-package.

I may be missing something of course!

**Comment by dkoszewnik** [comment]
Thanks very much for the suggestion.  This is now released in v2.3.1.
