### ISSUE TITLE
ArrayIndexOutOfBoundsException while building hash index

### ISSUE THREAD

**Issue by mikemuske** [Netflix/hollow#464]
My team has defined a hash index for the `Item` type composed of a single field: `classification.department_id`.

When building the hash index at application start up we get the following stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 375
	at com.netflix.hollow.core.memory.encoding.FixedLengthElementArray.getElementValue(FixedLengthElementArray.java:132)
	at com.netflix.hollow.core.memory.encoding.FixedLengthElementArray.getElementValue(FixedLengthElementArray.java:110)
	at com.netflix.hollow.core.read.engine.object.HollowObjectTypeReadStateShard.readFixedLengthFieldValue(HollowObjectTypeReadStateShard.java:165)
	at com.netflix.hollow.core.read.engine.object.HollowObjectTypeReadStateShard.readOrdinal(HollowObjectTypeReadStateShard.java:80)
	at com.netflix.hollow.core.read.engine.object.HollowObjectTypeReadState.readOrdinal(HollowObjectTypeReadState.java:144)
	at com.netflix.hollow.core.index.HollowHashIndexBuilder.getMatchHash(HollowHashIndexBuilder.java:394)
	at com.netflix.hollow.core.index.HollowHashIndexBuilder.buildIndex(HollowHashIndexBuilder.java:120)
	at com.netflix.hollow.core.index.HollowHashIndex.reindexHashIndex(HollowHashIndex.java:70)
	at com.netflix.hollow.core.index.HollowHashIndex.<init>(HollowHashIndex.java:61)
	at com.tgt.oss.autobahn.hollow.consumer.HashIndexRefreshListener$HollowHashIndexCreator.generateIndex(HashIndexRefreshListener.java:153)
	at com.tgt.oss.autobahn.hollow.consumer.HashIndexRefreshListener.initHashIndexes(HashIndexRefreshListener.java:77)
	at com.tgt.oss.autobahn.hollow.consumer.HashIndexRefreshListener.refreshSuccessful(HashIndexRefreshListener.java:57)
	at com.netflix.hollow.api.client.HollowClientUpdater.updateTo(HollowClientUpdater.java:161)
	at com.netflix.hollow.api.consumer.HollowConsumer.triggerRefresh(HollowConsumer.java:179)
```
Debugging revealed that `HollowHashIndexBuilder.buildIndex()` was able to successfully process the first 32 populated ordinals for the `Item` type, but the 33rd caused the above exception. Inspecting the data I was able to see that the 33rd ordinal `Item` had a null classification field.

The problem seems to be in the path traversal happening in `HollowHashIndexBuilder.getMatchHash()`. When the ordinal for the `Classification` member of `Item` ordinal 33 is retrieved, it is -1 since that field is null. Since the field path has multiple components, an attempt is made to retrieve the `String department_id` ordinal from the `Classification` ordinal of -1, which causes the above exception.  I noticed two other places where this problem happens as well.

I believe this pull request addresses the issue: https://github.com/Netflix/hollow/pull/463

**Comment by tcataldo** [comment]
Hi, we encountered a pretty similar issue in our software which uses hollow 3.4.5:

```
2020-07-27 12:18:08,388 [vert.x-worker-thread-12] n.b.e.m.e.e.ExecuteExecutor ERROR - orig: LogonContext{mapiCtx=5aca4cf6-54e6-4241-9a9d-22940bb60a49, authN=xxxx@blue-mind.net, authZ=xxxx@bluemind.net, replID=1, publicFolder=false}, upd: LogonContext{mapiCtx=5aca4cf6-54e6-4241-9a9d-22940bb60a49, authN=xxxx@blue-mind.net, authZ=xxxx@blue-mind.net, replID=1, publicFolder=false} Rop processing error 3
java.lang.ArrayIndexOutOfBoundsException: 3
        at com.netflix.hollow.core.memory.encoding.FixedLengthElementArray.getElementValue(FixedLengthElementArray.java:134)
        at com.netflix.hollow.core.memory.encoding.FixedLengthElementArray.getElementValue(FixedLengthElementArray.java:112)
        at com.netflix.hollow.core.read.engine.object.HollowObjectTypeReadStateShard.readFixedLengthFieldValue(HollowObjectTypeReadStateShard.java:165)
        at com.netflix.hollow.core.read.engine.object.HollowObjectTypeReadStateShard.readOrdinal(HollowObjectTypeReadStateShard.java:80)
        at com.netflix.hollow.core.read.engine.object.HollowObjectTypeReadState.readOrdinal(HollowObjectTypeReadState.java:145)
        at net.bluemind.directory.hollow.datamodel.consumer.AddressBookRecordTypeAPI.getUidOrdinal(AddressBookRecordTypeAPI.java:73)
        at net.bluemind.directory.hollow.datamodel.consumer.AddressBookRecordDelegateLookupImpl.getUidOrdinal(AddressBookRecordDelegateLookupImpl.java:21)
        at net.bluemind.directory.hollow.datamodel.consumer.AddressBookRecord.getUid(AddressBookRecord.java:23)
        at net.bluemind.exchange.provider.core.CoreProvider.getUserSettings(CoreProvider.java:1232)
        at net.bluemind.exchange.ese.ConstantProperties.get(ConstantProperties.java:91)
        at net.bluemind.exchange.mapi.emsmdb.execute.RopGetPropertiesSpecific.buildMailboxValues(RopGetPropertiesSpecific.java:194)
        at net.bluemind.exchange.mapi.emsmdb.execute.RopGetPropertiesSpecific.handle(RopGetPropertiesSpecific.java:117)
        at net.bluemind.exchange.mapi.emsmdb.execute.ExecuteExecutor.lambda$1(ExecuteExecutor.java:171)
        at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:52)
        at net.bluemind.exchange.mapi.emsmdb.execute.ExecuteExecutor.execute(ExecuteExecutor.java:171)
        at net.bluemind.exchange.mapi.emsmdb.execute.ExecuteExecutor.lambda$0(ExecuteExecutor.java:71)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:276)

```

As the exceptions looks pretty similar, could it be an hollow bug ?

**Comment by tcataldo** [comment]
I see that the PR you reference is merged. But as your issue is still open, I'm wondering if it fixed everything for you. As I don't have a reproducer for the stack I added in my previous comment, I'm not willing to perform a blind upgrade of our hollow stack.
