### ISSUE TITLE
NullPointer - Hollow History UI

### ISSUE THREAD

**Issue by marcuscavalcanti** [Netflix/hollow#72]
Hi guys, I'm getting a NullPointerException when I access Hollow History UI.

I'm using hollow-reference-implementation (hollow lib version: 2.6.8).

Complete stacktrace:

`java.lang.NullPointerException
	at com.netflix.hollow.tools.history.keyindex.HollowHistoryTypeKeyIndex.queryIndexedFields(HollowHistoryTypeKeyIndex.java:218)
	at com.netflix.hollow.history.ui.pages.HistoryQueryPage.typeQueryKeyMatches(HistoryQueryPage.java:65)
	at com.netflix.hollow.history.ui.pages.HistoryQueryPage.setUpContext(HistoryQueryPage.java:47)
	at com.netflix.hollow.history.ui.pages.HistoryPage.render(HistoryPage.java:54)
	at com.netflix.hollow.history.ui.HollowHistoryUI.handle(HollowHistoryUI.java:151)
	at com.netflix.hollow.history.ui.jetty.HollowHistoryHandler.handle(HollowHistoryHandler.java:38)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)`

Everything works fine with Hollow Explorer UI.

**Comment by dkoszewnik** [comment]
Thanks for the report.  I was able to reproduce this error by attempting to use the **Lookup Key** field in the `HollowHistoryUI` prior to the first state update (before any change history is available).

Does that sound consistent with your issue?  Can you please confirm whether or not this error goes away after an update occurs?

**Comment by marcuscavalcanti** [comment]
@dkoszewnik you're totally right, with one snapshot version history-ui worked very well.

**Comment by ghost** [comment]
Resolved by #203. Thanks for the original report!
